### ISSUE TITLE
SV_StartSound Spam error

### ISSUE THREAD

**Issue by ElPapuh** [Scags/TF2-Jailbreak-Redux#78] opened 2019-04-16 08:30 UTC
I need help to fix this
![Sin título](https://user-images.githubusercontent.com/26206183/56194161-a1c22f80-6032-11e9-8df2-be2663c634ca.jpg)

**Comment by RWolfyo** [comment] 2019-04-17 17:43
Duplicate of #68

**Comment by ElPapuh** [comment] 2019-04-18 07:03
@RWolfyo I know, but I don't see any fix for it, I don't see the music cvar mentioned on #68

**Comment by Scags** [comment] 2019-08-03 08:17
As of 1.14 this should be fixed. Never once got an instance of it during testing.

**Closed by Scags** 2019-08-03 08:17 UTC
